#!/bin/sh
# 2. Identify and display the Ethernet interface characteristics:
# (a) Identify broadcast address
# The ifconfig utility is used to assign an address to a network interface and/or configure network interface parameters.

ifconfig | grep broadcast | awk '{print $6}'
