#!/bin/sh
# (b) Identify all IP adresses which are part of the same subnet
# in bash the $ stands for ‘substitute contents.’
# $()   -evaluate commands and substitute the result in place of what's in the ()
# $(()) 	- evaluate arithmetically
ping $(ifconfig en0 | grep broadcast | awk '{print $6}') -c 1 > /dev/null && arp -ai en0 | awk '{print $2}' | tr -d '()'
