#!/bin/sh
# 4. Identifiy the default gateway in the routing table
# 
# We can use netstat to show various network data tables
# r shows the routing table
# n shows them without interpretation, as numbers

netstat -rn | grep default | awk 'NR == 1 {print}'