#!/bin/sh
# 11. Use the output of the previous command to find the name and 
# IP address of the device that makes the link between you (local network)
# and the outside world

traceroute lists each device between mine and the destination, the 
last devices using internal ip ranges ((ip of this machine & netmask) from q 02)
is the router doing the network address translation between the local area 
network  and the external network which is
 nat (10.60.1.1)