#!/bin/sh
# 12. Find the IP that was assigned to you by dhcp server

# CIADDR means Client IP Address

# ipconfig getpacket
# Prints to standard output the DHCP/BOOTP packet that the client
# 	accepted from the DHCP/BOOTP server.

ipconfig getpacket en0 | grep yiaddr | awk '{print $3}'
