#!/bin/sh
# 5. Name the command that determines the state of the SSH service.

# Use the ps command to list all the processes and filter the output
# using grep to check if the SSH process is running.
# ps aux | grep sshd

sudo service ssh status

# or
# /etc/init.d/ssh status