#!/bin/sh
# 7. Figure out the PID of the SSHD service.

# The pgrep command finds processes by name and returns the PID for each match

pgrep sshd

# or
# cat /var/run/sshd.pid
# or 
# ps aux | grep sshd
# or 
# pgrep sshd
