#!/bin/sh
# 7. Figure out the PID of the SSHD service.

# The pgrep command finds processes by name and returns the PID for each match

cat /var/run/sshd.pid


# ps aux | grep sbin/sshd
# or
# cat /var/run/sshd.pid
# or 
# pgrep sshd 
# or 
# pgrep sshd
