#!/bin/sh
# 12. Figure out the exact size of each folder of /var in a humanly
#	understandable way followed by the path of it.
# The du utility displays the file system block usage
# for each file argument and for each directory in the
# file hierarchy rooted in each directory argument.
du -h /var/*
