#!/bin/sh
# 14. Run the ‘tail -f /var/log/syslog‘ command in background
# A background process is one that the shell does not wait on. To run a
# background process, we append “&” at the end of the process we want
# to start:

tail -f /var/log/syslog &
