#!/bin/sh
# 16. Find the service which makes it possible to run specific tasks
#	following a regular schedule

cron

# cron wakes up every minute and goes through crontabs checkings which tasks
# should be ran
