#!/bin/bash
# 1. Write a script which displays only the login, UID and Path of each
# 	entry of the /etc/passwd file.

#	mark:x:1001:1001:mark,,,:/home/mark:/bin/bash
#	[--] - [--] [--] [-----] [--------] [--------]
#	|    |   |    |     |         |        |
#	|    |   |    |     |         |        +-> 7. Login shell
#	|    |   |    |     |         +----------> 6. Home directory
#	|    |   |    |     +--------------------> 5. GECOS
#	|    |   |    +--------------------------> 4. GID
#	|    |   +-------------------------------> 3. UID
#	|    +-----------------------------------> 2. Password
#	+----------------------------------------> 1. Username

# GID, primary group id
# GECOS, comment field, typically used to record general information about the 
# account or its user(s) such as their real name and phone number. 

cut -d: -f 1,3,7 /etc/passwd | tr ':' '\t'

# 6 instead of 7 lists user home directory, which is a path aswell ¯\_(ツ)_/¯
