#!/bin/bash
# 2. Write a script which delete an ACTIVE user on the VM.

read -p "Who do you want to nuke? " user
read -p "Are you quite sure? yes/no " confirmation
if [ "confirmation" == "yes" ]
then
	killall -u $user
	crontab -r -u $user
	userdel -r $user
else
	echo "Just kidding! $user is fine."
	exit 0
fi
echo "$user's processes killed, their home, mail and crontab tasks spool removed."